export enum UserFetchsActions {
  ADD_NEW_FETCH_FOR_EXPLORE = 'ADD_NEW_FETCH_FOR_EXPLORE',
  ADD_NEW_FETCH_FOR_EXPLORE_SUCCESS = 'ADD_NEW_FETCH_FOR_EXPLORE_SUCCESS',
  ADD_FETCH_RESULT = 'ADD_FETCH_RESULT',
  WATCH_FETCH = 'WATCH_FETCH'
}