

export namespace MqApiConstants {

    export const MQ_METHOD_NAME_METADATA = "MQ:METHOD:NAME:METADATA";
    export const MQ_METHOD_GATEWAY_METADATA = "MQ:METHOD:GATEWAY:METADATA";
    export const MQ_METHOD_CONSUMER_METADATA = "MQ:METHOD:CONSUMER:METADATA";
    export const MQ_METHOD_PRODUCER_METADATA = "MQ:METHOD:PRODUCER:METADATA";

}
