

export namespace MqGwConstants {

    export const MQ_GW_METHOD_UUID_METADATA = "MQ:GW:METHOD:UUID:METADATA";
    export const MQ_GW_METHOD_NAME_METADATA = "MQ:GW:METHOD:NAME:METADATA";
    export const MQ_GW_METHOD_GATEWAY_METADATA = "MQ:GW:METHOD:GATEWAY:METADATA";
    export const MQ_GW_METHOD_CLIENT_METADATA = "MQ:GW:METHOD:CLIENT:METADATA";
    export const MQ_GW_METHOD_CONSUMER_METADATA = "MQ:GW:METHOD:CONSUMER:METADATA";
    export const MQ_GW_METHOD_PRODUCER_METADATA = "MQ:GW:METHOD:PRODUCER:METADATA";

}
